###服务注册名称
eureka:
###客户端调用地址
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
###eureka 服务端口号
server:
  port: 8100
Spring:
  appliction:
    name:service-zuul
zuul:
  routes:
    api-a:
      path:/api-member/**
      service-id:service-member
    api-b:
      path:/api-order/**
      service-id:service-order
